version: "3"

x-deploy-data:
  envSchema:
    required:
      - CONFIG
      - MONGODB_URL
    properties:
      CONFIG:
        type: string
        format: code/yaml
        description: The config that describes how to generate the graphql server
        default: |
          schema: |
            type User {
              _id: ObjectId
              name: String
            }
          types:
            User:
              collection: users
      MONGODB_URL:
        type: string
        description: The url to connect the database, it will be kept encrypted
        pattern: ^(mongodb:(?:\/{2})?)((\w+?):(\w+?)@|:?@?)(\S+?):(\d+)\/(\S+?)(\?replicaSet=(\S+?))?$$
        default: mongodb://yourdatabaseurl/database-name

services:
  mongoke:
    image: gcr.io/containerful/mongoke
    environment:
      - PYTHONUNBUFFERED=1
      - DB_URL=${MONGODB_URL}
      - CONFIG=${CONFIG}
