
version: '3'

services:
    graphql-server:
        build: .
        # image: mongoke
        # entrypoint: sh -c 'pip install tartiflette==1.0.0rc1 && python -m mongoke /conf.yml && ls generated/generated/sdl/*'
        # entrypoint: pip show tartiflette
        command: /conf.yml
        volumes: 
            - ./confs/testing.yaml:/conf.yml
            - ./confs/schema.graphql:/schema.graphql
        environment: 
            - PYTHONUNBUFFERED=1
            - DB_URL=mongodb://mongo/db
    mongo:
        image: mongo
        logging: 
            driver: none

