
version: '3'

services:
    graphql-server:
        build: .
        # entrypoint: sh -c 'pip install tartiflette==1.0.0rc1 && python -m mongoke /conf.yml && ls generated/generated/sdl/*'
        # entrypoint: pip show tartiflette
        command: /conf.yml
        volumes: 
            - ./confs/testing.yaml:/conf.yml
            - ./confs/skema:/skema
        environment: 
            - PYTHONUNBUFFERED=1
    mongo:
        image: mongo
        logging: 
            driver: none

CONFIG:
    skema: |
        User:
            _id: ObjectId
            username: Str
            email: Str
        BlogPost:
            _id: ObjectId
            author_id: ObjectId
            content: Str
    types:
        User:
            collection: users
        BlogPost:
            collection: posts
    relations:
        -   field: posts
            from: User
            to: BlogPost
            where:
                author_id: ${{ parent['_id'] }}
